-- Add stats columns to managed_games
ALTER TABLE managed_games ADD COLUMN IF NOT EXISTS likes INTEGER DEFAULT 0;
ALTER TABLE managed_games ADD COLUMN IF NOT EXISTS gamepass_sales INTEGER DEFAULT 0;
ALTER TABLE managed_games ADD COLUMN IF NOT EXISTS total_robux INTEGER DEFAULT 0;
ALTER TABLE managed_games ADD COLUMN IF NOT EXISTS playing INTEGER DEFAULT 0;
ALTER TABLE managed_games ADD COLUMN IF NOT EXISTS visits INTEGER DEFAULT 0;